spring.datasource.url=jdbc:postgresql://localhost:5432/rideease_dev
spring.datasource.username=Vaibhav
spring.datasource.password=%qazwsxedc%123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

kafka.topic.rideBooked=ride.booked
kafka.topic.rideCompleted=ride.completed
kafka.bootstrap-servers=localhost:9092
kafka.admin.fatalIfBrokerNotAvailable = true
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.auto-startup=true




# Global logging level off
logging.level.root=INFO

# Enable only Kafka-related logs
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO

